version: "3"

services:
  postgres:
    env_file: .env
    image: postgres:12.4
    container_name: words-cup
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}

    volumes:
      - ./postgres:/var/lib/postgresql/data

volumes:
  postgres_data:
